// AUTO-GENERATED by config/generateI18nModuleTypes.ts (prepare:types hook). Do not edit.
// Source: i18n/locales/en/*.json — add a file there and restart dev (or run `npx nuxt prepare`).
export type I18nModuleType = 'common' | 'csgo.catalog' | 'dota2.catalog' | 'rust.catalog' | 'tf2.catalog';
